sudo: required
language: cpp
notifications:
  email: false
  slack:
    secure: Vd9YKWhC8eRvQ4l0MC1HkjFYqOrN4ZL00zLFMcu//j/kttyEHl0bekjVyWZaTWISJtSq+5UzDyhXjrDOIkKr5coCO4qL3HDc7t2ksSNwfzcHG0ErMW4ho2VtbN8OTfwhwSV5EUdgfqokgg9ONMPeHYsqVZgEYr2TQuDius5zJ/aoiAStuc2hUrTu2z9he4hXcYGCmlbNN0kfBPE2PV/RdZfFLYlfgjKVm0ztInLdGAvWjJY69YTt72Ubt5arrgfFLa/j8/gtvYwwVJ9PaMdExeI62ulplsmqt9kZ8vW6SScHg6vVwj79WExS4s4suXvrF7bUDtqjzeiBU+zDPDgFSFk0f0o9qAc4DiA2er+jEDHM8Q3G/JTdp2ODQMSYWfOX/LAK2TnyqIhGAeNHtwgyTidAGdwAtmgrIHUVan/c366nbJ9Y/GzYepouTUA1VzRnjiI+Qla8u/rJfN230YffHxXmeNnsgc5/Rt4F3gK9rKQFkaDZp86WaiIn6WWG8jatCHgl4ya4o5mlcn4Ftw7ZVv7xkAm58MXpx47BWDb3OcI0ML1ige7ixTBNG6q5Ah1FYHOguMW7JefJTrW60ZSHFupAI959prmaXkFfHu31KRzya/eGgG+Uag0u9Bjc1DUohoJdOFdrqyiK9exMWWnFU5US5Edv9uG8q0WVDZfhKGc=
install:
- git clone --branch v1.12.0 https://github.com/google/flatbuffers.git && cd flatbuffers
  && cmake -G "Unix Makefiles" && sudo make install && sudo cp flatc /usr/local/bin/
  && cd ..
script:
- sh compile.sh
